# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430 \u041f\u0440\u0435\u0434\u043c\u0435\u0442\u0443')),
                ('data_exam', models.DateField(null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0456 \u0447\u0430\u0441 \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u043d\u044f')),
                ('professor', models.CharField(max_length=256, verbose_name="\u0406\u043c'\u044f \u0432\u0438\u043a\u043b\u0430\u0434\u0430\u0447\u0430")),
                ('student_group', models.ManyToManyField(to='students.Group', verbose_name='\u0413\u0440\u0443\u043f\u0430')),
            ],
            options={
                'verbose_name': '\u0415\u043a\u0437\u0430\u043c\u0435\u043d\u0438',
                'verbose_name_plural': '\u0415\u043a\u0437\u0430\u043c\u0435\u043d\u0438',
            },
        ),
    ]
