# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='student_group',
            new_name='exam_group',
        ),
    ]
